### ISSUE TITLE
Create a video tutorial about running zend_oo on VirtualBox

### ISSUE THREAD

**Issue by PowerVANO** [HorizenOfficial/zend_oo#111]
_**This is a task for HDE**._

**Goals:**

- Create a tutorial video for zend_oo which includes all the points described below in the scope of work.

**Scope of Work**

- Show exact VirtualBox settings (minimum RAM, HDD, CPU)
- Installation of VirtualBox Guest Additions to resolve display issues
- zend_oo must be fully built on a local machine from the sidechains_testnet branch (no out of memory errors)
- Show steps needed to configure and run zend to fully sync with sidechains testnet (which involves a config file change)
- Ideally VirtualBox should be running on a Mac, but Windows is fine as well

**Schedule/Milestones**

This task should be completed within 4 weeks once accepted. If a user does not complete this task within the allotted time, it will be considered open for another user to complete. For the task to be considered complete, it will need to be reviewed and approved by the Horizen team. The team may request edits be made to the video before approval. 

Users that accept this task must provide weekly updates during the period they are working on the task. 

**Budget: $250 USD (Paid in ZEN)**

**Comment by luisantoniocrag** [comment]
Hey! Can I take this task?

**Comment by PowerVANO** [comment]
> Hey! Can I take this task?

Hey @luisantoniocrag! Yes, you can!
Please confirm if you take this task and provide weekly updates.

**Comment by luisantoniocrag** [comment]
sure!

**Comment by PowerVANO** [comment]
Ok @luisantoniocrag. This task is yours then. Looking forward to your updates.

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO,

I have worked on the steps for the video tutorial.

Can I do it with Ubuntu? Or does there have to be some other OS installed on virtualBox?

https://gist.github.com/luisantoniocrag/1ea735b4d98d50f13e35b5b6508c6a49

**Comment by PowerVANO** [comment]
Hi @luisantoniocrag Ubuntu is fine as a guest OS inside VirtualBox. Please use Bionic one though (18).

For host OS you should be running VirtualBox on Mac OS or on Windows.

**Comment by Dule-Dev** [comment]
Hey, can I take on this task?

**Comment by Mlhozgr** [comment]
Hello PowerNano!
Can i contribute?

**Comment by PowerVANO** [comment]
Hi @Dule-Dev and @Mlhozgr 
Not yet. This task has been claimed by @luisantoniocrag. If he cannot finish the task, then it will be open again and you will be able to start working on it.

@luisantoniocrag Can you please update about your progress so far?

**Comment by SouL-H** [comment]
Hello @PowerVANO 

I think the project can be received by 1 person. Will there be other projects like this?

**Comment by PowerVANO** [comment]
Hi @SouL-H There will be more tasks in the near future, of course! Please monitor https://hde.horizen.io/ regularly.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 

Do you have any updates regarding the task progression on your end?

**Comment by luisantoniocrag** [comment]
Hi @PowerVANO , sorry I have been a bit busy but I already have the video I just need to add some editing (some cuts and I will share it with you).

**Comment by PowerVANO** [comment]
Great to heat that @luisantoniocrag! Looking forward to your video!

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO I have noticed that this msg on my console.

`Error: This version has been deprecated as of block height 831936. You should upgrade to the lastest version of Zen. To disable deprecation for this version, set -disabledeprecation=2.1.0-beta4.`


is there something i need to update? or did I just mention that they need to set set `-disabledeprecation = 2.1.0-beta4.`

**Comment by luisantoniocrag** [comment]
I´m running on the lastest version of sidechains_testnet branch.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag 

Yes, please use "-disabledeprecation=2.1.0-beta4" switch as there won't be a new zend_oo release compatible with the existing sidechain testnet 1.

**Comment by JdevStudios** [comment]
Hey Zen Team, I want to throw my hat in the ring... how do I apply? 
Thanks.

**Comment by PowerVANO** [comment]
Hey @JdevStudios 

This task is taken already but I already replied in another one which you can take. 

Be sure to check other tasks on HDE website as well: https://hde.horizen.io/tasks

**Comment by luisantoniocrag** [comment]
Hey @PowerVANO  I will share with you the video URL tomorrow

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag, 

That's great!

**Comment by luisantoniocrag** [comment]
@PowerVANO 

There is the Video URL. Thanks for waiting. 
https://drive.google.com/file/d/1VJ3-pYhaYTUMiQvVDx8z-u-BWKdOa824/view?usp=sharing

I will be pending any request.

**Comment by PowerVANO** [comment]
> @PowerVANO
> 
> There is the Video URL. Thanks for waiting.
> https://drive.google.com/file/d/1VJ3-pYhaYTUMiQvVDx8z-u-BWKdOa824/view?usp=sharing
> 
> I will be pending any request.

Thank you! Please wait for our tech team's review and feedback.

**Comment by PowerVANO** [comment]
Hey @luisantoniocrag!

Your work has been accepted! Congratulations and thank you!

Please submit the bounty claim form from the HDE website.

**Comment by luisantoniocrag** [comment]
Done. Thank you.

**Comment by PowerVANO** [comment]
> Done. Thank you.

Your bounty will be paid in the coming days. Thank you.

Closing the issue.

**Comment by 2enter** [comment]
Hey, I want to participate if it's still available.

**Comment by PowerVANO** [comment]
@luisantoniocrag Bounty paid. Thanks for your contribution!

@2enter Bounty is no longer available unfortunately. It has been completed and paid already. Please have a look at HDE for more bounties: https://hde.horizen.io/
