### ISSUE TITLE
Duplicated "scTxsCommitment" field in the JSON response of the getblock RPC command

### ISSUE THREAD

**Issue by ptagl** [HorizenOfficial/zend_oo#174]
The JSON response returned by the `getblock` call contains duplicated entries for the `scTxsCommitment` field ([here](https://github.com/HorizenOfficial/zend_oo/blob/c5c914091f43e722b63067068b39b0efcb9a6938/src/rpc/blockchain.cpp#L153) and [here](https://github.com/HorizenOfficial/zend_oo/blob/c5c914091f43e722b63067068b39b0efcb9a6938/src/rpc/blockchain.cpp#L195)).

It seems like the duplication has been accidentally introduced when merging #72.

**Comment by cronicc** [comment]
Closed in #175
