### ISSUE TITLE
Verify correctness of SC VK and Proof

### ISSUE THREAD

**Issue by DanieleDiBenedetto** [HorizenOfficial/zend_oo#24]
Imported from https://github.com/ZencashOfficial/zen/issues/292

**Comment by alsala** [comment]
The check performed by:

    bool IsValidScProof(const ScProof& scProof)

Should be enhanced including also a check on the proof size, for example:

    if (scProof.empty() || scProof.size() != zendoo_get_field_size_in_bytes())
        return false;

If scProof vector is empty, failing to check this may lead to a crash in the proof verification

**Comment by ptagl** [comment]
The checks over the proof object have been improved after the refactoring work started with commit e43ff6cb364dcfefd7a81d955ba51a0801d00dee.
