### ISSUE TITLE
getrawtransaction $txid 1 doesn't work with certificate transactions

### ISSUE THREAD

**Issue by cronicc** [HorizenOfficial/zend_oo#36]
Certificate transactions currently can't be decoded with `getrawtransaction`, for that the rpc call `getrawcertificate` was added. Yet we still display the certificate transaction IDs in e.g. `getrawmempool`.

This could break automated scripts that expect to be able to decode all transactions listed in `getrawmempool` or in `getblock` using `getrawtransaction $txid 1`.

It should be possible to extend `getrawtransaction`/`decoderawtransaction` and possibly also `decodescript` to also decode certificate transactions.

**Comment by ptagl** [comment]
The `getrawtransaction` command can now correctly decode also certificates.
