### ISSUE TITLE
zen-cli command getscinfo: wrong values in the result for attributes "epoch" and "end epoch height" for CEASED sidechains 

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/zend_oo#38]
If a sidechain is CEASED, its data returned from the  command **getscinfo** has wrong values for the following fields:
"epoch" 
"end epoch height"
(the fields continue to "evolve" as the sidechain would be ALIVE, but should refer to the last alive epoch)

example:
getscinfo 67e17645d1481322e1f30b90f2c2c2fa55478d7c3fc4bbefbc2f8390d89844ea

{
  "scid": "67e17645d1481322e1f30b90f2c2c2fa55478d7c3fc4bbefbc2f8390d89844ea",
  "balance": 1337.00000000,
  **"epoch": 158,
  "end epoch height": 677884,**
  "state": "CEASED",
  "ceasing height": 662105,
  "creating tx hash": "6e3a5c3112ea14960f62195f5e107bc818a619f87772b2debd578fd7bceec5d0",
  "created in block": "001736f8f91e44b6f6a4bd070f58067bd6429e9cce68fbfe24fcceadd9008210",
  "created at block height": 661985,
  "last certificate epoch": -1,
  "last certificate hash": "0000000000000000000000000000000000000000000000000000000000000000",
  "withdrawalEpochLength": 100,
   ......
}

**Comment by abi87** [comment]
@Cermelli  @annagiuliaber  this is fixed already in sidechains_dev. Please close the issue
