### ISSUE TITLE
zen-cli command sc_create: help is not clear on which is the minimum value for a valid withdrawalEpochLength

### ISSUE THREAD

**Issue by alsala** [HorizenOfficial/zend_oo#42]
Tried to run sc_create cli command on testnet. got the error

 Invalid withdrawalEpochLength, less that minimum value allowed 

. Had to manually guess what that withdrawalEpochLength was. It ended up being 100. That error should print out the min value as it clearly is checking it somewhere. The comman description should be extended to be more informative.

**Comment by annagiuliaber** [comment]
Issue fixed with PR #52 Fixed up getscinfo for ceased sidechains
