### ISSUE TITLE
zen-cli command getscinfo: add support for filter out ceased sidechains and for pagination

### ISSUE THREAD

**Issue by paolocappelletti** [HorizenOfficial/zend_oo#44]
zen-cli rpc command **getscinfo** (when invoked without a specific scid) should support optional parameters for filter out ceased  sidechains and limit the response array:
- onlyAlive (boolean - default false) : if set to true the CEASED sidechains are filtered from the result
- from  (integer) : if set, limit the starting item index in the result array to this (included) (0 based)
- to (integer) : if set, limit the ending item index in the result array to this (excluded) (0 based)

To be coherent with the new explorer endpoint, the result should also be changed to this format:
```
{
"totalItems":95,
"from":0,
"to":50,
"items":[
   .......
  ]
}
```

**Comment by abi87** [comment]
@Cermelli @annagiuliaber this can be closed down as it is already implemented in sidechains_dev
