### ISSUE TITLE
Ceased SC Withdrawal of FTs posted after the last valid epoch (an epoch with a valid and non voided certificate)

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/zend_oo#93]
To allow the withdrawal of FTs happened after the last valid certificate, we should allow the prover to enforce having submitted a FT after the last block of the last valid epoch. For allowing this we should pass as public input the cumulative ScTXCommTree of the last block and the one where the sidechain had ceased.

**Comment by ptagl** [comment]
This issue is obsolete since the current implementation just uses one `ScTxCommTree`, in particular the one of the block where the sidechain had ceased.

See commit 71a1d3c77ace20e670a6594a2b294c0559cea0b0 for details.
