### ISSUE TITLE
Wallet CreateTransaction CSWs full support

### ISSUE THREAD

**Issue by i-Alex** [HorizenOfficial/zend_oo#95]
Current implementation of `bool CWallet::CreateTransaction` has several issues with CSWs:
1) If the initial transaction (like the one passed via `fundrawtransaction`) contains CSWs which total amount already covers total outputs amount (vouts and ccouts), `CreateTransaction` will try to fund a negative value of `totalOutputValue`
2) If the initial transaction contains CSWs and the `sign` argument of the method is `true`, the fund inputs message to sign will not include CSWs data, so the resulting signatures will be invalid.

**Comment by ptagl** [comment]
This issue has been fixed with PR #126.
